# Generated by Django 6.0.2 on 2026-02-09 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_options_alter_employee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(default='', max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(default='Tunisie', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Téléphone d'urgence"),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salaire net'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Téléphone personnel'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rib',
            field=models.CharField(default='', max_length=30, verbose_name='RIB'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default='', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='advance_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'avance"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='advance_reason',
            field=models.TextField(blank=True, default='', verbose_name="Motif de l'avance"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cin',
            field=models.CharField(default='00000000', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cin', message='Le CIN doit contenir 8 chiffres', regex='^\\d{8}$')], verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance sur salaire'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
