# Generated by Django 6.0.2 on 2026-02-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='net_salary',
        ),
    ]
