# Generated by Django 6.0.2 on 2026-02-09 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense')], max_length=10)),
            ],
            options={
                'verbose_name': 'Catégorie de Transaction',
                'verbose_name_plural': 'Catégories de Transaction',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre de Caisse',
                'verbose_name_plural': 'Registres de Caisse',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Dépense'), ('salary', 'Salaire'), ('investment', 'Investissement'), ('other', 'Autre')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField()),
                ('receipt', models.FileField(blank=True, upload_to='receipts/')),
                ('verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transactioncategory')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
